# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Edson Junior
author-title: Web Develop
gravatar: 95eef2ad27ac806bf77e5b837ddc47ec
email: junior.si16@gmail.com
twitter: juniorsi16
github: roinuj16
facebook: Roinuj16
linkedin: roinuj16
bio: "I'm graduated in Information System.
Always taste improve and update my knowledge for this reason I am always taking courses and taste also exchange experiences and knowledge with those around me.
I'm Back-End Developer with PHP, but I like Front End."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 4
  - name: jQuery
    level: 4
  - name: Angular
    level: 3
  - name: Bootstrap
    level: 4
  - name: Gulp
    level: 3
  - name: Grunt
    level: 3
  - name: Bower
    level: 3

back-end:
  - name: PHP
    level: 4
  - name: Node.js
    level: 2
  - name: SQL
    level: 4

mobile:
  - name: Apache Cordova
    level: 2
  - name: Ionic
    level: 1

db:
  - name: MySQL
    level: 4
  - name: PostgreSQL
    level: 3
  - name: SQL Server
    level: 2
  - name: Oracle
    level: 3

devops:
  - name: Docker
    level: 3
  - name: Vagrant
    level: 3
  - name: Jenkins
    level: 1
  - name: Git
    level: 4

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 3
  - name: RUP
    level: 3

others:
  - name: REST
    level: 3
  - name: Symfony
    level: 3
  - name: Twig
    level: 4
  - name: Doctrine ORM
    level: 3
  - name: Laravel, Blade, Eloquent ORM
    level: 3
# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]